# Generated by Django 3.2.2 on 2022-06-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web3', '0002_auto_20220615_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(max_length=255, unique=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_started', to='web3.wallet', verbose_name='从'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_received', to='web3.wallet', verbose_name='到'),
        ),
    ]
