# Generated by Django 3.2.2 on 2022-06-19 17:14

from django.db import migrations, models
import django.db.models.deletion
import xyz_util.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('web3', '0003_auto_20220616_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='abi',
            field=xyz_util.modelutils.JSONField(blank=True, default={}, verbose_name='ABI'),
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='web3.contract', verbose_name='合约'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfttransactions', to='web3.contract', verbose_name='合约'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='web3.contract', verbose_name='合约'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_sent', to='web3.wallet', verbose_name='从'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(db_index=True, max_length=64, verbose_name='方法'),
        ),
    ]
