# Generated by Django 3.2.2 on 2022-06-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web3', '0005_auto_20220623_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='已验'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='网站用户'),
        ),
    ]
