# Generated by Django 3.2.2 on 2022-07-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web3', '0007_auto_20220706_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='web3.nft', verbose_name='数字藏品'),
        ),
        migrations.AddField(
            model_name='nft',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nfts', to='web3.contract', verbose_name='合约'),
        ),
        # migrations.AddField(
        #     model_name='contract',
        #     name='standard',
        #     field=models.ForeignKey(blank=True, default='', max_length=64, verbose_name='标准'),
        # ),
        migrations.AlterField(
            model_name='collection',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web3.contract', verbose_name='合约'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='url',
            field=models.URLField(max_length=255, verbose_name='地址'),
        ),
        migrations.RunSQL("""
        update web3_nft a,
web3_collection b
set a.contract_id=b.contract_id
where a.collection_id=b.id
"""),
        migrations.RunSQL("""
        insert ignore into web3_nft(contract_id,token_id) 
        select distinct contract_id,token_id 
        from web3_event 
        where nft_id is null
        """),
        migrations.RunSQL("""
        update web3_event a,
web3_nft b
set a.nft_id = b.id
where a.contract_id =b.contract_id
and a.token_id=b.token_id
""")
    ]
